server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: portal-server
  config:
    import: optional:classpath:docker/.env[.properties]
  cloud:
    nacos:
      discovery: #启用 spring cloud nacos discovery
        server-addr: ${NACOS_IP}:${NACOS_PORT}
        namespace: ${NACOS_NAMESPACE}
        username: ${NACOS_USERNAME}
        password: ${NACOS_PASS}
        watch:
          enabled: true
        enabled: ${NACOS_ENABLE}
        group: ${NACOS_GROUP}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DB}
    username: ${PG_USER}
    password: ${PG_PASS}
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1
  flyway:
    enabled: true
    encoding: UTF-8
    # 可以支持多个location, 用','隔开
    locations: classpath:db/migration
    # migrate是否校验
    validate-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASS}
      database: 0
      timeout: 3000
  security:
    user:
      name: admin
      password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  docker:
    compose:
      enabled: true
      file: classpath:docker/compose.yaml
springdoc:
  api-docs:
    enabled: true
    version: openapi_3_1
    path: /api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLE}
    path: /swagger-ui
logging:
  level:
    root: info
  file:
    path: ./logs
    name: ${logging.file.path}/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/%d{yyyy-MM-dd}/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
      max-file-size: 50MB
      max-history: 30
      total-size-cap: 5GB
