name: Setup Environment
description: Setup environment to check and build Halo, including console and core projects.

inputs:
  java-version:
    description: Java version.
    required: false
    default: "21"

runs:
  using: "composite"
  steps:
    - name: Setup graalvm
      uses: graalvm/setup-graalvm@v1
      with:
        distribution: "liberica"
        cache: "gradle"
        java-version: ${{ inputs.java-version }}
        java-package: 'jdk+fx'
