name: portal-server
services:
  redis:
    container_name: redis
    image: redis:7
    healthcheck:
      test: [ "CMD" , "redis-cli" , "--raw" , "incr" , "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./volumes/redis/data:/data:Z
      - ./volumes/redis/logs:/logs:Z
    #配置文件启动
    command: redis-server --logfile /logs/redis.log --requirepass ${REDIS_PASS} --bind 0.0.0.0
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  postgres:
    container_name: postgres
    image: postgres:15
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_PORT=${PG_PORT}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    ports:
      - ${PG_PORT}:${PG_PORT}
